// <auto-generated>
// This code was partially generated by a tool.
// </auto-generated>

namespace YoutubeDLSharp.Options
{
    public partial class OptionSet
    {
        private Option<string> username = new Option<string>("-u", "--username");
        private Option<string> password = new Option<string>("-p", "--password");
        private Option<string> twofactor = new Option<string>("-2", "--twofactor");
        private Option<bool> netrc = new Option<bool>("-n", "--netrc");
        private Option<string> videoPassword = new Option<string>("--video-password");

        /// <summary>
        /// Login with this account ID
        /// </summary>
        public string Username { get => username.Value; set => username.Value = value; }
        /// <summary>
        /// Account password. If this option is
        /// left out, youtube-dl will ask
        /// interactively.
        /// </summary>
        public string Password { get => password.Value; set => password.Value = value; }
        /// <summary>
        /// Two-factor authentication code
        /// </summary>
        public string TwoFactor { get => twofactor.Value; set => twofactor.Value = value; }
        /// <summary>
        /// Use .netrc authentication data
        /// </summary>
        public bool Netrc { get => netrc.Value; set => netrc.Value = value; }
        /// <summary>
        /// Video password (vimeo, youku)
        /// </summary>
        public string VideoPassword { get => videoPassword.Value; set => videoPassword.Value = value; }
    }
}
