// <auto-generated>
// This code was partially generated by a tool.
// </auto-generated>

using System;

namespace YoutubeDLSharp.Options
{
    public partial class OptionSet
    {
        private Option<bool> writeLink = new Option<bool>("--write-link");
        private Option<bool> writeUrlLink = new Option<bool>("--write-url-link");
        private Option<bool> writeWeblocLink = new Option<bool>("--write-webloc-link");
        private Option<bool> writeDesktopLink = new Option<bool>("--write-desktop-link");

        /// <summary>
        /// Write an internet shortcut file, depending
        /// on the current platform (.url, .webloc or
        /// .desktop). The URL may be cached by the OS
        /// </summary>
        public bool WriteLink { get => writeLink.Value; set => writeLink.Value = value; }
        /// <summary>
        /// Write a .url Windows internet shortcut. The
        /// OS caches the URL based on the file path
        /// </summary>
        public bool WriteUrlLink { get => writeUrlLink.Value; set => writeUrlLink.Value = value; }
        /// <summary>
        /// Write a .webloc macOS internet shortcut
        /// </summary>
        public bool WriteWeblocLink { get => writeWeblocLink.Value; set => writeWeblocLink.Value = value; }
        /// <summary>
        /// Write a .desktop Linux internet shortcut
        /// </summary>
        public bool WriteDesktopLink { get => writeDesktopLink.Value; set => writeDesktopLink.Value = value; }
    }
}
