// <auto-generated>
// This code was partially generated by a tool.
// </auto-generated>

using System;

namespace YoutubeDLSharp.Options
{
    public partial class OptionSet
    {
        private Option<string> sponsorblockMark = new Option<string>("--sponsorblock-mark");
        private Option<string> sponsorblockRemove = new Option<string>("--sponsorblock-remove");
        private Option<string> sponsorblockChapterTitle = new Option<string>("--sponsorblock-chapter-title");
        private Option<bool> noSponsorblock = new Option<bool>("--no-sponsorblock");
        private Option<string> sponsorblockApi = new Option<string>("--sponsorblock-api");

        /// <summary>
        /// SponsorBlock categories to create chapters
        /// for, separated by commas. Available
        /// categories are sponsor, intro, outro,
        /// selfpromo, preview, filler, interaction,
        /// music_offtopic, poi_highlight, all and
        /// default (=all). You can prefix the category
        /// with a &quot;-&quot; to exclude it. See [1] for
        /// description of the categories. E.g.
        /// --sponsorblock-mark all,-preview [1] https:/
        /// /wiki.sponsor.ajay.app/w/Segment_Categories
        /// </summary>
        public string SponsorblockMark { get => sponsorblockMark.Value; set => sponsorblockMark.Value = value; }
        /// <summary>
        /// SponsorBlock categories to be removed from
        /// the video file, separated by commas. If a
        /// category is present in both mark and remove,
        /// remove takes precedence. The syntax and
        /// available categories are the same as for
        /// --sponsorblock-mark except that &quot;default&quot;
        /// refers to &quot;all,-filler&quot; and poi_highlight is
        /// not available
        /// </summary>
        public string SponsorblockRemove { get => sponsorblockRemove.Value; set => sponsorblockRemove.Value = value; }
        /// <summary>
        /// MPLATE
        /// An output template for the title of the
        /// SponsorBlock chapters created by
        /// --sponsorblock-mark. The only available
        /// fields are start_time, end_time, category,
        /// categories, name, category_names. Defaults
        /// to &quot;[SponsorBlock]: %(category_names)l&quot;
        /// </summary>
        public string SponsorblockChapterTitle { get => sponsorblockChapterTitle.Value; set => sponsorblockChapterTitle.Value = value; }
        /// <summary>
        /// Disable both --sponsorblock-mark and
        /// --sponsorblock-remove
        /// </summary>
        public bool NoSponsorblock { get => noSponsorblock.Value; set => noSponsorblock.Value = value; }
        /// <summary>
        /// SponsorBlock API location, defaults to
        /// https://sponsor.ajay.app
        /// </summary>
        public string SponsorblockApi { get => sponsorblockApi.Value; set => sponsorblockApi.Value = value; }
    }
}
