// <auto-generated>
// This code was partially generated by a tool.
// </auto-generated>

using System;

namespace YoutubeDLSharp.Options
{
    public partial class OptionSet
    {
        private Option<string> username = new Option<string>("-u", "--username");
        private Option<string> password = new Option<string>("-p", "--password");
        private Option<string> twoFactor = new Option<string>("-2", "--twofactor");
        private Option<bool> netrc = new Option<bool>("-n", "--netrc");
        private Option<string> videoPassword = new Option<string>("--video-password");
        private Option<string> apMso = new Option<string>("--ap-mso");
        private Option<string> apUsername = new Option<string>("--ap-username");
        private Option<string> apPassword = new Option<string>("--ap-password");
        private Option<bool> apListMso = new Option<bool>("--ap-list-mso");

        /// <summary>
        /// Login with this account ID
        /// </summary>
        public string Username { get => username.Value; set => username.Value = value; }
        /// <summary>
        /// Account password. If this option is
        /// left out, youtube-dl will ask
        /// interactively.
        /// </summary>
        public string Password { get => password.Value; set => password.Value = value; }
        /// <summary>
        /// Two-factor authentication code
        /// </summary>
        public string TwoFactor { get => twoFactor.Value; set => twoFactor.Value = value; }
        /// <summary>
        /// Use .netrc authentication data
        /// </summary>
        public bool Netrc { get => netrc.Value; set => netrc.Value = value; }
        /// <summary>
        /// Video password (vimeo, youku)
        /// </summary>
        public string VideoPassword { get => videoPassword.Value; set => videoPassword.Value = value; }
        /// <summary>
        /// Adobe Pass multiple-system operator (TV
        /// provider) identifier, use --ap-list-mso
        /// for a list of available MSOs
        /// </summary>
        public string ApMso { get => apMso.Value; set => apMso.Value = value; }
        /// <summary>
        /// Multiple-system operator account login
        /// </summary>
        public string ApUsername { get => apUsername.Value; set => apUsername.Value = value; }
        /// <summary>
        /// Multiple-system operator account
        /// password. If this option is left out,
        /// youtube-dl will ask interactively.
        /// </summary>
        public string ApPassword { get => apPassword.Value; set => apPassword.Value = value; }
        /// <summary>
        /// List all supported multiple-system
        /// operators
        /// </summary>
        public bool ApListMso { get => apListMso.Value; set => apListMso.Value = value; }
    }
}
