// <auto-generated>
// This code was partially generated by a tool.
// </auto-generated>

namespace YoutubeDLSharp.Options
{
    public partial class OptionSet
    {
        private Option<bool> writeThumbnail = new Option<bool>("--write-thumbnail");
        private Option<bool> writeAllThumbnails = new Option<bool>("--write-all-thumbnails");
        private Option<bool> listThumbnails = new Option<bool>("--list-thumbnails");

        /// <summary>
        /// Write thumbnail image to disk
        /// </summary>
        public bool WriteThumbnail { get => writeThumbnail.Value; set => writeThumbnail.Value = value; }
        /// <summary>
        /// Write all thumbnail image formats to
        /// disk
        /// </summary>
        public bool WriteAllThumbnails { get => writeAllThumbnails.Value; set => writeAllThumbnails.Value = value; }
        /// <summary>
        /// Simulate and list all available
        /// thumbnail formats
        /// </summary>
        public bool ListThumbnails { get => listThumbnails.Value; set => listThumbnails.Value = value; }
    }
}
